# Generated by Django 3.0 on 2020-02-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigneditem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
