# Generated by Django 3.0 on 2020-02-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_item_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_accepted',
            field=models.BooleanField(null=True),
        ),
    ]
