# Generated by Django 3.0 on 2020-02-20 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0005_auto_20200220_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_employee', to='myapp1.Employee')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_item', to='myapp1.Item')),
            ],
        ),
    ]
